export const  data =[
    {
        postId:1,
        gamerName: 'Bertie Yates',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-2_ipcjws.jpg',
        game:'Fortnite',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        skins:['Level 1279', '129 Skins', 'Skull Trooper, Candy Axe, Rabbit Raider', 'Full Access - chicksfnc203' ],
        images:['https://cdn-offer-photos.zeusx.com/d7b7f290-af35-4194-856f-edb24f206e8c.jpg', 'https://pbs.twimg.com/media/D238eu8XQAAAl9-.jpg'],
        rating: 5.0,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price:45,
        isSold: true,
        contact: '0900-78601'
    },
    {
        postId:2,
        gamerName: 'Hester Hogan',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-3_rxtqvi.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Fortnite',
        skins:['[PC] Fortnite', '1479 Level', '120+ Outfits', 'Glow', 'Wonder', 'Minty Axe [chicksgfor10092]'],
        rating: 4.3,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 30,
        isSold: true,
        contact: '0900-78601'
    },
    {
        postId:3,
        gamerName: 'Larry Little',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883423/person-4_t9nxjt.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Escape From Tarkov',
        skins:['[Global] Escape From Tarkov', '(0 hours played)', 'Original Email'],
        rating: 3.7,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 56,
        isSold: true,
        contact: '0900-78601'
      
    },
    {
        postId:4,
        gamerName: 'Sean Walsh',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Pubg',
        skins:['LEVEL 58','CLOTH SET 27','GUN SKINS 16', 'HELMET 1','BAG 5 TWITTER LOGIN CHEAPEST AND SAFE INSTANT DELIVERY'],
        rating: 2.9,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 63,
        isSold: true,
        contact: '0900-78601'
    },
    {
        postId:5,
        gamerName: 'Lola Gardner',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883334/person-1_rfzshl.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Free Fire',
        skins:[' Level 62', 'Diamond2 S24','Gold3 S10', '36 Characters', 'Gun Legend Skins', 'Many Amazing Items+Pets', '10 Times Elite', 'Safe&Legal'],
        rating: 4,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 72,
        isSold: false,
        contact: '0900-78601'
    },
    {
        postId:6,
        gamerName: 'Bertie Yates',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-2_ipcjws.jpg',
        game:'Fortnite',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        skins:['Level 1279', '129 Skins', 'Skull Trooper, Candy Axe, Rabbit Raider', 'Full Access - chicksfnc203' ],
        images:['https://cdn-offer-photos.zeusx.com/d7b7f290-af35-4194-856f-edb24f206e8c.jpg', 'https://pbs.twimg.com/media/D238eu8XQAAAl9-.jpg'],
        rating: 5.0,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price:45,
        isSold: false,
        contact: '0900-78601'
    },
    {
        postId:7,
        gamerName: 'Hester Hogan',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-3_rxtqvi.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Fortnite',
        skins:['[PC] Fortnite', '1479 Level', '120+ Outfits', 'Glow', 'Wonder', 'Minty Axe [chicksgfor10092]'],
        rating: 4.3,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 30,
        isSold: false,
        contact: '0900-78601'
    },
    {
        postId:8,
        gamerName: 'Larry Little',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883423/person-4_t9nxjt.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Escape From Tarkov',
        skins:['[Global] Escape From Tarkov', '(0 hours played)', 'Original Email'],
        rating: 3.7,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 56,
        isSold: false,
        contact: '0900-78601'
      
    },
    {
        postId:9,
        gamerName: 'Sean Walsh',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Pubg',
        skins:['LEVEL 58','CLOTH SET 27','GUN SKINS 16', 'HELMET 1','BAG 5 TWITTER LOGIN CHEAPEST AND SAFE INSTANT DELIVERY'],
        rating: 2.9,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 63,
        isSold: false,
        contact: '0900-78601'
    },
    {
        postId:10,
        gamerName: 'Lola Gardner',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883334/person-1_rfzshl.jpg',
        title: 'Level 1595 | 172 Skins | IKONIK, Merry Mint Axe, Skull Trooper | Full Access - chicksfnc279',
        game:'Free Fire',
        skins:[' Level 62', 'Diamond2 S24','Gold3 S10', '36 Characters', 'Gun Legend Skins', 'Many Amazing Items+Pets', '10 Times Elite', 'Safe&Legal'],
        rating: 4,
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis, id. Explicabo, a facere neque incidunt labore fuga facilis, aspernatur nulla distinctio aut quisquam nemo deleniti tempora quos, ut officia? Pariatur!' ,
        price: 72,
        isSold: false,
        contact: '0900-78601'
    },
  ];